name = "GCR Opt-In"
type = "custom"
client_id = "f862751401a81b080930d35cd29f694b"
organization_id = "4293454"
application_url = "https://shopify-gcr-script.vercel.app"
embedded = false

[auth]
  redirect_urls = ["https://shopify-gcr-script.vercel.app"]
  scopes = ["read_checkouts","read_orders"]
[webhooks]
topic = "APP_UNINSTALLED"
address = "https://example.com/webhooks/app_uninstalled"
format = "json"
api_version = "2026-01"